/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Lens types for categorizing findings.
 * Ordered alphabetically to match steward-core's Ord implementation.
 */
export const enum LensType {
  AccountabilityOwnership = 0,
  BoundariesSafety = 1,
  DignityInclusion = 2,
  RestraintPrivacy = 3,
  TransparencyContestability = 4
}
/** Rule evaluation result types. */
export const enum RuleResult {
  Satisfied = 0,
  Violated = 1,
  Uncertain = 2,
  NotApplicable = 3
}
/** Source of evidence for findings. */
export const enum EvidenceSource {
  Contract = 0,
  Output = 1,
  Context = 2,
  Metadata = 3
}
/** Evidence supporting a rule evaluation. */
export interface Evidence {
  source: EvidenceSource
  claim: string
  pointer: string
}
/** Result of evaluating a single rule. */
export interface RuleEvaluation {
  ruleId: string
  ruleText?: string
  result: RuleResult
  evidence: Array<Evidence>
  rationale?: string
}
/** State of a single lens after evaluation. */
export interface LensState {
  stateType: string
  reason?: string
  violation?: string
}
/** Finding from a single lens evaluation. */
export interface LensFinding {
  lens?: LensType
  questionAsked?: string
  state: LensState
  rulesEvaluated: Array<RuleEvaluation>
  confidence: number
}
/** Findings from all five lenses. */
export interface LensFindings {
  dignityInclusion: LensFinding
  boundariesSafety: LensFinding
  restraintPrivacy: LensFinding
  transparencyContestability: LensFinding
  accountabilityOwnership: LensFinding
}
/** Boundary violation details. */
export interface BoundaryViolation {
  lens: LensType
  ruleId: string
  ruleText: string
  evidence: Array<Evidence>
  accountableHuman: string
}
/** The evaluation state: Proceed, Escalate, or Blocked. */
export interface State {
  stateType: string
  summary?: string
  uncertainty?: string
  decisionPoint?: string
  options?: Array<string>
  violation?: BoundaryViolation
}
/** The complete result of evaluating an output against a contract. */
export interface EvaluationResult {
  state: State
  lensFindings: LensFindings
  confidence: number
  evaluatedAt: string
}
/**
 * Evaluate an output against a stewardship contract.
 *
 * This is the main entry point for Steward evaluation.
 */
export declare function evaluate(contract: Contract, output: Output): EvaluationResult
/** Evaluate with optional context and metadata. */
export declare function evaluateWithContext(contract: Contract, output: Output, context?: Array<string> | undefined | null, metadata?: Record<string, string> | undefined | null): EvaluationResult
/** Check if an evaluation result is Proceed. */
export declare function isProceed(stateType: string): boolean
/** Check if an evaluation result is Escalate. */
export declare function isEscalate(stateType: string): boolean
/** Check if an evaluation result is Blocked. */
export declare function isBlocked(stateType: string): boolean
/** A stewardship contract defining rules for AI evaluation. */
export declare class Contract {
  /** Create a Contract from a YAML string. */
  static fromYaml(yaml: string): Contract
  /** Create a Contract from a YAML file. */
  static fromYamlFile(path: string): Contract
  /** Get the contract name. */
  get name(): string
  /** Get the contract version. */
  get version(): string
  /** Get the contract purpose. */
  get purpose(): string
  /** Get the accountable human email. */
  get accountableHuman(): string
}
/** AI-generated output to be evaluated. */
export declare class Output {
  /** Create a text output. */
  static text(content: string): Output
  /** Get the output content. */
  get content(): string
}
